### ISSUE TITLE
i3-vim-focus: command not found

### ISSUE THREAD

**Issue by RidaAyed** [jwilm/i3-vim-focus#4]
Followed the instructions by adding the settings in .vimrc, .bashrc and compiled the rust package.

```bash
$ cd ~/.vim/bundle/i3-vim-focus/i3-vim-focus/src
$ i3-vim-focus left
-bash: i3-vim-focus: command not found
```

**Comment by jwilm** [comment]
You need to put the binary somewhere on your path. It builds to `target/release/i3-vim-focus`.
